security:
    enable_authenticator_manager: true
    providers:
        app_user_provider:
            entity:
                class: 'App\Domains\User\Entity'
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            json_login:
                check_path: /login
                username_path: email
                password_path: password
    password_hashers:
        App\Domains\User\Entity:
            algorithm: auto
